apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: manifests.dagger.emblica.fi
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: dagger.emblica.fi
  # version name to use for REST API: /apis/<group>/<version>
  version: v0beta1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: manifests
    # singular name to be used as an alias on the CLI and for display
    singular: manifest
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DaggerManifest
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - dm


---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: runs.dagger.emblica.fi
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: dagger.emblica.fi
  # version name to use for REST API: /apis/<group>/<version>
  version: v0beta1
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: runs
    # singular name to be used as an alias on the CLI and for display
    singular: run
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: DaggerRun
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - dr
