apiVersion: batch/v1
kind: Job
metadata:
  name: testjob
  namespace: default
  ownerReferences:
  - apiVersion: dagger.emblica.fi/v0beta1
    blockOwnerDeletion: true
    controller: true
    kind: DaggerRun
    name: dagger-run-name
    uid: dagger-run-uid
  labels:
    jobscheduler: dagger
spec:
  template:
    metadata:
      namespace: default
      labels:
        task-id: testtaskid
        run: testrun
        manifest: testmanifest
        jobscheduler: dagger
    spec:
      volumes:
      - name: state
        emptyDir: {}
      - name: input
        emptyDir: {}
      - name: output
        emptyDir: {}
      restartPolicy: "OnFailure"
      initContainers:
      - name: load-input
        image: docker.io/emblica/dagger-stateloader
        command: ["./loader.sh"]
        volumeMounts:
        - name: state
          mountPath: /state
        - name: input
          mountPath: /input
      containers:
      - name: workload
        image: busybox
        volumeMounts:
          - name: state
            mountPath: /state
          - name: input
            mountPath: /input
          - name: output
            mountPath: /output
      - name: save-state
        image: docker.io/emblica/dagger-stateloader
        command: ["./saver.sh"]
        imagePullPolicy: Always
        volumeMounts:
          - name: state
            mountPath: /state
          - name: output
            mountPath: /output
        env:
        - name: RANDOM_ENV
          value: "value"
